<a href="https://colab.research.google.com/github/emmenets/neuralnetwork/blob/master/Einfuehrung_in_Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install tensorflow

In [2]:
pip install virtualenv

     |████████████████████████████████| 2.0MB 2.8MB/s 


In [3]:
cd ~

/root


In [0]:
ls

In [0]:
mkdir envs

In [6]:
!virtualenv ~/envs/tensorflow

Using base prefix '/usr'
New python executable in /root/envs/tensorflow/bin/python3
Also creating executable in /root/envs/tensorflow/bin/python
Installing setuptools, pip, wheel...
done.


In [0]:
!source ~/envs/tensorflow/bin/activate

In [8]:
pip install tensorflow

In [9]:
ls

envs/


In [10]:
import tensorflow as tf
print(tf.__version__)

1.14.0


In [0]:
from tensorflow.examples.tutorials.mnist import input_data

In [0]:
DATA_DIR = '/tmp/data'
NUM_STEPS = 1000
MINIBATCH_SIZE = 100

In [13]:
data = input_data.read_data_sets(DATA_DIR, one_hot=True)

W0714 07:45:49.253166 140558492518272 deprecation.py:323] From <ipython-input-13-e7f1e451c50e>:1: read_data_sets (from tensorflow.contrib.learn.python.learn.datasets.mnist) is deprecated and will be removed in a future version.
Instructions for updating:
Please use alternatives such as official/mnist/dataset.py from tensorflow/models.
W0714 07:45:49.255481 140558492518272 deprecation.py:323] From /usr/local/lib/python3.6/dist-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py:260: maybe_download (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated and will be removed in a future version.
Instructions for updating:
Please write your own downloading logic.
W0714 07:45:49.258345 140558492518272 deprecation.py:323] From /usr/local/lib/python3.6/dist-packages/tensorflow/contrib/learn/python/learn/datasets/base.py:252: _internal_retry.<locals>.wrap.<locals>.wrapped_fn (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated and will be remove

Successfully downloaded train-images-idx3-ubyte.gz 9912422 bytes.
Extracting /tmp/data/train-images-idx3-ubyte.gz


W0714 07:45:50.040413 140558492518272 deprecation.py:323] From /usr/local/lib/python3.6/dist-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py:267: extract_labels (from tensorflow.contrib.learn.python.learn.datasets.mnist) is deprecated and will be removed in a future version.
Instructions for updating:
Please use tf.data to implement this functionality.
W0714 07:45:50.047479 140558492518272 deprecation.py:323] From /usr/local/lib/python3.6/dist-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py:110: dense_to_one_hot (from tensorflow.contrib.learn.python.learn.datasets.mnist) is deprecated and will be removed in a future version.
Instructions for updating:
Please use tf.one_hot on tensors.


Successfully downloaded train-labels-idx1-ubyte.gz 28881 bytes.
Extracting /tmp/data/train-labels-idx1-ubyte.gz
Successfully downloaded t10k-images-idx3-ubyte.gz 1648877 bytes.
Extracting /tmp/data/t10k-images-idx3-ubyte.gz


W0714 07:45:50.375870 140558492518272 deprecation.py:323] From /usr/local/lib/python3.6/dist-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py:290: DataSet.__init__ (from tensorflow.contrib.learn.python.learn.datasets.mnist) is deprecated and will be removed in a future version.
Instructions for updating:
Please use alternatives such as official/mnist/dataset.py from tensorflow/models.


Successfully downloaded t10k-labels-idx1-ubyte.gz 4542 bytes.
Extracting /tmp/data/t10k-labels-idx1-ubyte.gz


In [14]:
print(data)

Datasets(train=<tensorflow.contrib.learn.python.learn.datasets.mnist.DataSet object at 0x7fd6196b3390>, validation=<tensorflow.contrib.learn.python.learn.datasets.mnist.DataSet object at 0x7fd60dbfbb00>, test=<tensorflow.contrib.learn.python.learn.datasets.mnist.DataSet object at 0x7fd60d5729e8>)


In [15]:
x = tf.placeholder(tf.float32, [None, 784])
W = tf.Variable(tf.zeros([784, 10]))

y_true = tf.placeholder(tf.float32, [None, 10])
y_pred = tf.matmul(x, W)

cross_entropy = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(logits=y_pred, labels=y_true))

gd_step = tf.train.GradientDescentOptimizer(0.5).minimize(cross_entropy)

correct_mask = tf.equal(tf.argmax(y_pred, 1), tf.argmax(y_true, 1))
accuracy = tf.reduce_mean(tf.cast(correct_mask, tf.float32))

with tf.Session() as sess:
  
  #Train
  sess.run(tf.global_variables_initializer())
  
  for _ in range(NUM_STEPS):
    batch_xs, batch_ys = data.train.next_batch(MINIBATCH_SIZE)
    sess.run(gd_step, feed_dict={x: batch_xs, y_true: batch_ys})
    
  #Test
  ans = sess.run(accuracy, feed_dict={x: data.test.images, y_true: data.test.labels})
  
  print("Genauigkeit: {:.4}%".format(ans*100))



W0714 07:45:50.758857 140558492518272 deprecation.py:323] From <ipython-input-15-0f82147eaf58>:7: softmax_cross_entropy_with_logits (from tensorflow.python.ops.nn_ops) is deprecated and will be removed in a future version.
Instructions for updating:

Future major versions of TensorFlow will allow gradients to flow
into the labels input on backprop by default.

See `tf.nn.softmax_cross_entropy_with_logits_v2`.



Genauigkeit: 91.59%


In [16]:
a = tf.constant(5.0)
b = tf.constant(7.0)

c = tf.multiply(a,b)
d = tf.sin(c)
e = tf.divide(b,d)

sess = tf.Session()
outs = sess.run(e)
sess.close()
print("Ausgaben = {}".format(outs))

Ausgaben = -16.348163604736328


In [17]:
g = tf.Graph()
a = tf.constant(5)

print(a.graph is g)
print(a.graph is tf.get_default_graph())

False
True


In [18]:
g1 = tf.get_default_graph()
g2 = tf.Graph()

print(g1 is tf.get_default_graph())

with g2.as_default():
  print(g1 is tf.get_default_graph())
  
print(g1 is tf.get_default_graph())

True
False
True


In [19]:
a = tf.constant(5)
b = tf.constant(2)
c = tf.constant(3)

d = tf.multiply(a,b)
e = tf.add(c,b)
f = tf.subtract(d,e)

with tf.Session() as sess:
  fetches = [a,b,c,d,e,f]
  outs = sess.run(fetches)
  
print("Ausgaben = {}".format(outs))
print(type(outs[0]))

Ausgaben = [5, 2, 3, 10, 5, 5]
<class 'numpy.int32'>


In [20]:
import numpy as np

c = tf.constant([[1.0,2,3],
                 [4,5,6]])

print("Eingabewerte aus Python-Liste: {}".format(c.get_shape()))

c = tf.constant(np.array([
    [[1,2,3],
     [4,5,6]],
    [[1,1,1],
     [2,2,2]]
    ]))

print("Eingabewerte aus 3D-NumPy-Feld: {}".format(c.get_shape()))

Eingabewerte aus Python-Liste: (2, 3)
Eingabewerte aus 3D-NumPy-Feld: (2, 2, 3)


In [21]:
sess = tf.InteractiveSession()
c = tf.linspace(0.0, 4.0, 9)
print("Inhalt von 'c':\n {}\n".format(c.eval()))
sess.close()

Inhalt von 'c':
 [0.  0.5 1.  1.5 2.  2.5 3.  3.5 4. ]



In [29]:
A = tf.constant([[1,2,3],[4,5,6]])
print(A.get_shape())

x = tf.constant([1,0,1])
print(x.get_shape())

x = tf.expand_dims(x,1)
print(x.get_shape())

sess = tf.InteractiveSession()
print(x.eval())
sess.close()

b = tf.matmul(A,x)

sess = tf.InteractiveSession()
print(b.eval())
sess.close()

(2, 3)
(3,)
(3, 1)
[[1]
 [0]
 [1]]
[[ 4]
 [10]]


In [32]:
with tf.Graph().as_default():
  c1 = tf.constant(4,dtype=tf.float64,name='c')
  c2 = tf.constant(4,dtype=tf.int32,name='c')
print(c1.name)
print(c2.name)

c:0
c_1:0


In [0]:
with tf.Graph().as_default():
  c1 = tf.constant(4,dtype=tf.float64,name='c')
  with tf.name_scope("prefix_name"):
    c2 = tf.constant(4,dtype=tf.float64,name='c')
    c3 = tf.constant(4,dtype=tf.float64,name='c')
    c4 = tf.multiply(c2,c3)
    
  with tf.Session() as sess:
    outs = sess.run(c4)
  
print(outs)
print(c1.name)
print(c2.name)
print(c3.name)


In [55]:
init_val = tf.random_normal((1,5),0,1)
var = tf.Variable(init_val, name='var')
print("vor run (): \n{}".format(var))

init = tf.global_variables_initializer()
with tf.Session() as sess:
  sess.run(init)
  post_var = sess.run(var)
  
print("\nnach run (): \n{}".format(post_var))

vor run (): 
<tf.Variable 'var_12:0' shape=(1, 5) dtype=float32_ref>

nach run (): 
[[-1.2176148   1.7634599  -0.75645167 -1.2732797  -0.98598814]]


In [64]:
x_data = np.random.randn(5,10)
w_data = np.random.randn(10,1)

with tf.Graph().as_default():
  x = tf.placeholder(tf.float32, shape=(5,10))
  w = tf.placeholder(tf.float32, shape=(10,1))
  b = tf.fill((5,1),-1.)
  xw = tf.matmul(x,w)
  
  xwb = xw + b
  s = tf.reduce_max(xwb)
  with tf.Session() as sess:
    outs = sess.run(s,feed_dict={x: x_data, w: w_data})
    
print("Ausgaben = {}".format(outs))

Ausgaben = 0.6072272062301636


In [66]:
!git clone https://github.com/seraj94ai/Train-Object-Detection-Classifier.git

Cloning into 'Train-Object-Detection-Classifier'...
remote: Enumerating objects: 482, done.
remote: Total 482 (delta 0), reused 0 (delta 0), pack-reused 482
Receiving objects: 100% (482/482), 30.90 MiB | 38.22 MiB/s, done.
Resolving deltas: 100% (234/234), done.


In [67]:
cd Train-Object-Detection-Classifier

/root/Train-Object-Detection-Classifier


In [70]:
import utils

ModuleNotFoundError: ignored

In [69]:
!python3 Object_detection_image.py

Traceback (most recent call last):
  File "Object_detection_image.py", line 29, in <module>
    from utils import label_map_util
ModuleNotFoundError: No module named 'utils'
